title: raquelFishes
subtitle: Personal site
description: >- # this means to ignore newlines until "baseurl:"
  Personal site of Raquel Peces (a.k.a. raquelFishes)

url: "https://raquelfishes.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

### Multi-Language config
#languages: ["es", "en"]
languages: ["es"]
default_lang: "es"
exclude_from_localizations: ["assets", "gallery", "_sass"]

urls:
    - text: about
      url: /about
    - text: blog
      url: /blog
    #- text: Gallery
    #  url: /gallery
    #- text: Shop
    #  url : /shop
    - text: contact
      url : /contact
    #- text: Styleguide
    #  url: /styleguide
    #- text: Get Started
    #  url: /get-started

# Edit these details

author_logo: profile.webp
author: Raquel Peces
author_name: Raquel
author_lastname: Peces
author_bio: Hi, my name is Raquel Peces. I am a Computer Graphics Engineer and a Violinist :D
author_email: "raquelpm23@gmail.com"
author_location: Madrid
author_website_url: "http://raquelfishes.github.com"

# Typewrite config
typewrite_htmlId: input-typewrite
typewrite_typeSpeed: 50
typewrite_backSpeed: 10
typewrite_backDelay: 5000
typewrite_startDelay: 200
typewrite_shuffle: true
typewrite_loop: true
typewrite_loopCount: Infinity
typewrite_cursorChar: '|'


author_work_experiences:
            - company_name: Next Limit
              company_logo: nextlimit.webp
              company_url: https://nextlimit.com
              visibility: true
            - company_name: Ilion Animation Studios
              company_logo: ilion.webp
              company_url: https://ilion.com
              visibility: true

author_education_details:
              - college_logo: urjc.webp
                college_name: URJC
                college_url: https://urjc.es
                visibility: true
              - college_logo: ucm.webp
                college_name: UCM
                college_url: https://ucm.es
                visibility: true

                
# author_project_details:
#               - project_thumbnail: gamershub.png
#                 project_title: Gamers Hub
#                 project_description: A Platform built for Gamers and Game Devs
#                 project_url: https://gamershub.in
#                 visibility: true
#               - project_thumbnail: hack4r.PNG
#                 project_title: Hack4r
#                 project_description: A Platform built for Hackers and Penetration Testers
#                 project_url: https://hack4r.com
#                 visibility: true

# social links
twitter_username: raquelFishes
github_username:  raquelFishes
facebook_username: null
linkedin_username: raquelpeces
behance_username: null
instagram_username: raquelfishes
medium_username: null
telegram_username: null
dribbble_username: null
flickr_username: null
spotify_username: rapemu
spotify_playlist: 1PbDnV1w31gf9blJcYxpWV

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )
# disqus_shortname: sujay-kundu
hyvor_talk_website_id: null

# wakatime username (coding activity)
wakatime_username: raquelfishes

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: xwkrklev

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-166953347-1

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
#algolia:
#  application_id: D9WA1YKTRQ
#  index_name: blog_posts # You can replace that with whatever name you want
#  files_to_exclude: []
#  nodes_to_index: 'article'
#  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 6
per_page: 6
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  #- jekyll-algolia
  - jekyll-menus
  - jekyll-multiple-languages-plugin


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
